# Generated by Django 6.0 on 2025-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
